apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment-ca
  labels:
    app: notes-app-ca
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-app-ca
  template:
    metadata:
      labels:
        app: notes-app-ca
    spec:
      containers:
      - name: notes-app-ca
        image: 471112967512.dkr.ecr.us-east-1.amazonaws.com/notes-app-ca:latest
        resources:
          requests:
            cpu: "300m"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000