name: NotesApp CI/CD

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalación de dependencias
        run: npm i

      - name: Ejecución de pruebas
        run: npm test

      - name: Get current tag
        id: get-current-tag
        uses: zingimmick/github-action-get-current-tag@v1
      
      - name: Print tag
        run: echo ${{steps.get-current-tag.outputs.tag}}